import * as THREE from 'three';

/**
 * Shared wave authoring data for the CPU sampler and the vertex shader.
 *
 * The phase rate is the deep-water angular frequency (omega), not an
 * arbitrary animation speed. A directional component is represented as a
 * Gerstner/trochoidal wave: its vertical displacement is A sin(theta), while
 * its horizontal displacement is Q A cos(theta) in the travel direction.
 *
 * GPU Gems 1 recommends keeping the sum of Q k A below one so adjacent
 * particles do not fold into loops. We use the equivalent per-component
 * `OCEAN_STEEPNESS / (k * waveCount)` formulation below; summing over all
 * components gives exactly OCEAN_STEEPNESS.
 */
export interface WaveComponent {
  readonly directionX: number;
  readonly directionZ: number;
  readonly amplitude: number;
  readonly wavelength: number;
  /** Deep-water angular frequency, omega = sqrt(g * k), in radians/sec. */
  readonly speed: number;
  readonly phaseOffset: number;
}

export interface OceanWaveSample {
  /** Surface height at the requested world-space x/z location. */
  readonly height: number;
  /** Vertical derivative with respect to the solved rest-space x coordinate. */
  readonly dx: number;
  /** Vertical derivative with respect to the solved rest-space z coordinate. */
  readonly dz: number;
  /** Breaking/foam potential from compression, curvature, and slope. */
  readonly foam: number;
  /** Surface normal in world space, computed from analytic Gerstner tangents. */
  readonly normalX: number;
  readonly normalY: number;
  readonly normalZ: number;
  /** World-space position generated by the solved rest-space point. */
  readonly displacedX: number;
  readonly displacedZ: number;
  /** Lagrangian point used to produce the sample. */
  readonly restX: number;
  readonly restZ: number;
  /** Positive area compression and signed crest curvature diagnostics. */
  readonly compression: number;
  readonly curvature: number;
}

export const OCEAN_SURFACE_LEVEL = 0;
export const OCEAN_GRAVITY = 9.81;
/** Global steepness/choppiness budget. Values at or below one avoid loops. */
export const OCEAN_STEEPNESS = 0.82;

const TWO_PI = Math.PI * 2;
const OCEAN_WAVE_COUNT = 8;
const NEWTON_ITERATIONS = 5;
const NEWTON_EPSILON = 1e-8;

function deepWaterAngularFrequency(wavelength: number): number {
  const waveNumber = TWO_PI / wavelength;
  return Math.sqrt(OCEAN_GRAVITY * waveNumber);
}

function createWave(
  directionX: number,
  directionZ: number,
  amplitude: number,
  wavelength: number,
  phaseOffset: number,
): WaveComponent {
  return {
    directionX,
    directionZ,
    amplitude,
    wavelength,
    speed: deepWaterAngularFrequency(wavelength),
    phaseOffset,
  };
}

export const OCEAN_WAVES: readonly WaveComponent[] = [
  createWave(0.9701425, 0.2425356, 0.42, 26, 0.0),
  createWave(0.4718579, 0.8816745, 0.24, 13, 1.7),
  createWave(-0.8, 0.6, 0.14, 6.8, 3.1),
  createWave(0.2, -0.98, 0.085, 4.1, -0.9),
  createWave(-0.9353294, -0.3537814, 0.05, 2.6, 2.2),
  createWave(0.702713, -0.711473, 0.028, 1.7, -1.5),
  createWave(0.39, 0.92, 0.019, 1.15, 0.4),
  createWave(-0.72, 0.69, 0.013, 0.88, -2.2),
];

/** Upper bound used to normalize the signed curvature signal. */
export const OCEAN_CURVATURE_SCALE = OCEAN_WAVES.reduce(
  (sum, wave) => sum + wave.amplitude * (TWO_PI / wave.wavelength) ** 2,
  0,
);

interface RestWaveEvaluation {
  readonly height: number;
  readonly displacementX: number;
  readonly displacementZ: number;
  readonly heightDerivativeX: number;
  readonly heightDerivativeZ: number;
  readonly dXdx: number;
  readonly dXdz: number;
  readonly dZdx: number;
  readonly dZdz: number;
  readonly curvature: number;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

function smoothstep(edge0: number, edge1: number, value: number): number {
  const t = clamp((value - edge0) / (edge1 - edge0), 0, 1);
  return t * t * (3 - 2 * t);
}

function evaluateOceanWaveAtRest(
  restX: number,
  restZ: number,
  elapsedSeconds: number,
): RestWaveEvaluation {
  let height = 0;
  let displacementX = 0;
  let displacementZ = 0;
  let heightDerivativeX = 0;
  let heightDerivativeZ = 0;
  let dXdx = 1;
  let dXdz = 0;
  let dZdx = 0;
  let dZdz = 1;
  let curvature = 0;

  for (const wave of OCEAN_WAVES) {
    const waveNumber = TWO_PI / wave.wavelength;
    const phase = (restX * wave.directionX + restZ * wave.directionZ) * waveNumber
      - elapsedSeconds * wave.speed
      + wave.phaseOffset;
    const sine = Math.sin(phase);
    const cosine = Math.cos(phase);
    const horizontalAmplitude = OCEAN_STEEPNESS / (waveNumber * OCEAN_WAVE_COUNT);
    const horizontalDerivative = -OCEAN_STEEPNESS / OCEAN_WAVE_COUNT * sine;
    const heightDerivative = wave.amplitude * waveNumber * cosine;

    height += wave.amplitude * sine;
    displacementX += horizontalAmplitude * cosine * wave.directionX;
    displacementZ += horizontalAmplitude * cosine * wave.directionZ;
    heightDerivativeX += heightDerivative * wave.directionX;
    heightDerivativeZ += heightDerivative * wave.directionZ;

    dXdx += horizontalDerivative * wave.directionX * wave.directionX;
    dXdz += horizontalDerivative * wave.directionX * wave.directionZ;
    dZdx += horizontalDerivative * wave.directionZ * wave.directionX;
    dZdz += horizontalDerivative * wave.directionZ * wave.directionZ;
    curvature += wave.amplitude * waveNumber * waveNumber * sine;
  }

  return {
    height,
    displacementX,
    displacementZ,
    heightDerivativeX,
    heightDerivativeZ,
    dXdx,
    dXdz,
    dZdx,
    dZdz,
    curvature,
  };
}

function sampleFoam(
  evaluation: RestWaveEvaluation,
): { readonly foam: number; readonly compression: number } {
  const determinant = evaluation.dXdx * evaluation.dZdz
    - evaluation.dXdz * evaluation.dZdx;
  const compression = clamp(1 - determinant, 0, 1);
  const compressionSignal = smoothstep(0.045, 0.34, compression);
  const curvatureSignal = smoothstep(
    0.08,
    0.55,
    Math.max(0, evaluation.curvature / OCEAN_CURVATURE_SCALE),
  );
  const slopeSignal = smoothstep(
    0.2,
    0.82,
    Math.hypot(evaluation.heightDerivativeX, evaluation.heightDerivativeZ),
  );

  return {
    compression,
    // The Jacobian and curvature dominate; slope only stabilizes foam on
    // lower-resolution meshes where the sharpest crest may be undersampled.
    foam: clamp(
      compressionSignal * 0.54 + curvatureSignal * 0.30 + slopeSignal * 0.16,
      0,
      1,
    ),
  };
}

function sampleAtRest(
  restX: number,
  restZ: number,
  elapsedSeconds: number,
): OceanWaveSample {
  const evaluation = evaluateOceanWaveAtRest(restX, restZ, elapsedSeconds);
  const foam = sampleFoam(evaluation);

  // Tangents to the Gerstner parameterization in world-space rest axes. The
  // order is intentional: cross(tangentZ, tangentX) keeps Y positive on a
  // flat surface and therefore produces a stable upward-facing normal.
  const tangentX = new THREE.Vector3(
    evaluation.dXdx,
    evaluation.heightDerivativeX,
    evaluation.dZdx,
  );
  const tangentZ = new THREE.Vector3(
    evaluation.dXdz,
    evaluation.heightDerivativeZ,
    evaluation.dZdz,
  );
  const normal = tangentZ.cross(tangentX).normalize();

  return {
    height: OCEAN_SURFACE_LEVEL + evaluation.height,
    dx: evaluation.heightDerivativeX,
    dz: evaluation.heightDerivativeZ,
    foam: foam.foam,
    normalX: normal.x,
    normalY: normal.y,
    normalZ: normal.z,
    displacedX: restX + evaluation.displacementX,
    displacedZ: restZ + evaluation.displacementZ,
    restX,
    restZ,
    compression: foam.compression,
    curvature: evaluation.curvature,
  };
}

/**
 * Evaluate a wave at a Lagrangian/rest-space point. This is the direct
 * counterpart of the vertex shader's sample and is useful for CPU/GPU parity
 * assertions; the public sampler below additionally solves world-space x/z.
 */
export function sampleOceanWaveAtRest(
  restX: number,
  restZ: number,
  elapsedSeconds: number,
): OceanWaveSample {
  return sampleAtRest(restX, restZ, elapsedSeconds);
}

/**
 * Sample the displaced surface at world-space x/z. Gerstner waves are not a
 * strict height function because they move vertices laterally, so invert the
 * horizontal mapping with a few Newton steps before evaluating height and the
 * analytic normal. The no-loop steepness budget keeps this solve stable.
 */
export function sampleOceanWave(
  x: number,
  z: number,
  elapsedSeconds: number,
): OceanWaveSample {
  let restX = x;
  let restZ = z;

  for (let iteration = 0; iteration < NEWTON_ITERATIONS; iteration += 1) {
    const evaluation = evaluateOceanWaveAtRest(restX, restZ, elapsedSeconds);
    const residualX = restX + evaluation.displacementX - x;
    const residualZ = restZ + evaluation.displacementZ - z;
    const determinant = evaluation.dXdx * evaluation.dZdz
      - evaluation.dXdz * evaluation.dZdx;
    if (Math.abs(determinant) < NEWTON_EPSILON) {
      break;
    }

    const correctionX = (
      evaluation.dZdz * residualX - evaluation.dXdz * residualZ
    ) / determinant;
    const correctionZ = (
      -evaluation.dZdx * residualX + evaluation.dXdx * residualZ
    ) / determinant;
    restX -= correctionX;
    restZ -= correctionZ;

    if (Math.hypot(correctionX, correctionZ) < NEWTON_EPSILON) {
      break;
    }
  }

  return sampleAtRest(restX, restZ, elapsedSeconds);
}

export function sampleOceanNormal(
  x: number,
  z: number,
  elapsedSeconds: number,
  target: THREE.Vector3 = new THREE.Vector3(),
): THREE.Vector3 {
  const wave = sampleOceanWave(x, z, elapsedSeconds);
  return target.set(wave.normalX, wave.normalY, wave.normalZ).normalize();
}

function glslFloat(value: number): string {
  const rounded = value.toFixed(9).replace(/0+$/, '').replace(/\.$/, '');
  if (rounded === '-0' || rounded === '') {
    return '0.0';
  }
  return rounded.includes('.') ? rounded : `${rounded}.0`;
}

/**
 * Generate the GLSL wave evaluator from OCEAN_WAVES. Keeping this function
 * next to the CPU implementation makes a changed wave table update both
 * paths in one place and gives parity tests a single source of truth.
 */
export function createOceanWaveShaderSource(): string {
  const waveTerms = OCEAN_WAVES.map((wave) => (
    `  addGerstnerWave(result, vec2(${glslFloat(wave.directionX)}, ${glslFloat(wave.directionZ)}), `
      + `${glslFloat(wave.amplitude)}, ${glslFloat(wave.wavelength)}, ${glslFloat(wave.speed)}, `
      + `${glslFloat(wave.phaseOffset)}, point, time);`
  )).join('\n');

  return /* glsl */ `
const float TWO_PI = ${glslFloat(TWO_PI)};
const float OCEAN_SURFACE_LEVEL = ${glslFloat(OCEAN_SURFACE_LEVEL)};
const float OCEAN_STEEPNESS = ${glslFloat(OCEAN_STEEPNESS)};
const float OCEAN_WAVE_COUNT = ${glslFloat(OCEAN_WAVE_COUNT)};
const float OCEAN_CURVATURE_SCALE = ${glslFloat(OCEAN_CURVATURE_SCALE)};

struct OceanWaveSample {
  float height;
  vec2 displacement;
  float heightDx;
  float heightDz;
  float dXdx;
  float dXdz;
  float dZdx;
  float dZdz;
  float curvature;
  float compression;
  float foam;
};

float oceanSmoothstep(float edge0, float edge1, float value) {
  return smoothstep(edge0, edge1, clamp(value, 0.0, 1.0));
}

void addGerstnerWave(
  inout OceanWaveSample result,
  vec2 direction,
  float amplitude,
  float wavelength,
  float angularFrequency,
  float phaseOffset,
  vec2 point,
  float time
) {
  float waveNumber = TWO_PI / wavelength;
  float phase = dot(point, direction) * waveNumber
    - time * angularFrequency + phaseOffset;
  float sine = sin(phase);
  float cosine = cos(phase);
  float horizontalAmplitude = OCEAN_STEEPNESS / (waveNumber * OCEAN_WAVE_COUNT);
  float horizontalDerivative = -OCEAN_STEEPNESS / OCEAN_WAVE_COUNT * sine;
  float heightDerivative = amplitude * waveNumber * cosine;

  result.height += amplitude * sine;
  result.displacement += horizontalAmplitude * cosine * direction;
  result.heightDx += heightDerivative * direction.x;
  result.heightDz += heightDerivative * direction.y;
  result.dXdx += horizontalDerivative * direction.x * direction.x;
  result.dXdz += horizontalDerivative * direction.x * direction.y;
  result.dZdx += horizontalDerivative * direction.y * direction.x;
  result.dZdz += horizontalDerivative * direction.y * direction.y;
  result.curvature += amplitude * waveNumber * waveNumber * sine;
}

OceanWaveSample sampleOceanWave(vec2 point, float time) {
  OceanWaveSample result;
  result.height = 0.0;
  result.displacement = vec2(0.0);
  result.heightDx = 0.0;
  result.heightDz = 0.0;
  result.dXdx = 1.0;
  result.dXdz = 0.0;
  result.dZdx = 0.0;
  result.dZdz = 1.0;
  result.curvature = 0.0;
  result.compression = 0.0;
  result.foam = 0.0;

${waveTerms}

  float determinant = result.dXdx * result.dZdz - result.dXdz * result.dZdx;
  result.compression = clamp(1.0 - determinant, 0.0, 1.0);
  float compressionSignal = oceanSmoothstep(0.045, 0.34, result.compression);
  float curvatureSignal = oceanSmoothstep(
    0.08,
    0.55,
    max(0.0, result.curvature / OCEAN_CURVATURE_SCALE)
  );
  float slopeSignal = oceanSmoothstep(
    0.2,
    0.82,
    length(vec2(result.heightDx, result.heightDz))
  );
  result.foam = clamp(
    compressionSignal * 0.54 + curvatureSignal * 0.30 + slopeSignal * 0.16,
    0.0,
    1.0
  );
  return result;
}

vec3 oceanNormal(OceanWaveSample wave) {
  vec3 tangentX = vec3(wave.dXdx, wave.heightDx, wave.dZdx);
  vec3 tangentZ = vec3(wave.dXdz, wave.heightDz, wave.dZdz);
  return normalize(cross(tangentZ, tangentX));
}
`;
}
